[workspace]
resolver = "2"
members = [
    "crates/clamsform",
    "crates/clamsform-core"
    ]
default-members = [
  "crates/*",
]

[workspace.dependencies]
polars = {version = "0.46.0", features = ["lazy"]}
thiserror = "2.0.11"
